# Generated by Django 2.2.6 on 2020-05-19 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocetakKviza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poetak_kviza', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 23, 10, 35, 371149, tzinfo=utc))),
            ],
        ),
    ]
