# Generated by Django 2.2.6 on 2020-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='lozinka'),
        ),
    ]
