# Generated by Django 2.2.6 on 2020-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kviz',
            name='vreme_posta',
        ),
        migrations.AddField(
            model_name='kviz',
            name='trajanje_kviza',
            field=models.PositiveIntegerField(default=False),
            preserve_default=False,
        ),
    ]
