# Generated by Django 2.2.6 on 2020-05-20 00:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0002_pocetakkviza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocetakkviza',
            name='id_korisnika',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pocetakkviza',
            name='id_kviza',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='kvizer.Kviz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pocetakkviza',
            name='poetak_kviza',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 0, 12, 11, 58469, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='pocetakkviza',
            unique_together={('id_kviza', 'id_korisnika')},
        ),
    ]
