# Generated by Django 2.2.6 on 2020-05-14 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0003_auto_20200514_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kviz',
            name='id_korisnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rezultat',
            name='id_korisnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
