# Generated by Django 2.2.6 on 2020-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0003_auto_20200423_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kviz',
            name='naziv',
            field=models.CharField(max_length=300),
        ),
    ]
