# Generated by Django 2.2.6 on 2020-05-20 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0003_auto_20200520_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocetakkviza',
            name='poetak_kviza',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
