# Generated by Django 2.2.6 on 2020-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0004_auto_20200514_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='godina',
            field=models.CharField(choices=[('Prva godina', 'Prva godina'), ('Druga godina', 'Druga godina'), ('Treća godina', 'Treća godina'), ('Četvrta godina', 'Četvrta godina')], default='Prva godina', max_length=40),
            preserve_default=False,
        ),
    ]
