# Generated by Django 2.2.6 on 2020-05-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0004_auto_20200520_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocetakkviza',
            name='poetak_kviza',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
