# Generated by Django 2.2.6 on 2020-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0005_auto_20200428_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='odgovor',
            name='odgovor',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
