# Generated by Django 2.2.6 on 2020-05-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0005_user_godina'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rezultat',
            unique_together={('id_kviza', 'id_korisnika')},
        ),
    ]
