# Generated by Django 2.2.6 on 2020-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0005_auto_20200520_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezultat',
            name='poetak_kviza',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='PocetakKviza',
        ),
    ]
