# Generated by Django 2.2.6 on 2020-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0006_auto_20200521_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezultat',
            name='radio_kviz',
            field=models.BooleanField(default='0'),
            preserve_default=False,
        ),
    ]
