# Generated by Django 2.2.6 on 2020-05-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0006_odgovor_odgovor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('Učenik', 'Učenik'), ('Profesor', 'Profesor')], max_length=200)),
                ('ime', models.CharField(max_length=200)),
                ('prezime', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('lozinka', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='kviz',
            name='id_korisnika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvizer.Korisnik'),
        ),
        migrations.CreateModel(
            name='Rezultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodovi', models.SmallIntegerField()),
                ('id_korisnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvizer.Korisnik')),
                ('id_kviza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvizer.Kviz')),
            ],
        ),
    ]
