# Generated by Django 2.2.6 on 2020-05-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvizer', '0007_rezultat_radio_kviz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezultat',
            name='radio_kviz',
            field=models.BooleanField(default=False),
        ),
    ]
